{
 "title": "ONTAP: MetroCluster",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(aggr_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, node)"
    }
   },
   {
    "name": "Aggr",
    "query": {
     "query": "label_values(aggr_new_status{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",node=~\"$Node\"}, aggr)"
    }
   },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Average Latency",
   "type": "stat",
   "description": "Average latency in microseconds for the WAFL filesystem to process all the operations on the volume; not including request processing or network communication time.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volume_avg_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write Latency",
   "type": "stat",
   "description": "Average RDMA write I/O latency.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(fcvi_rdma_write_avg_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write Throughput",
   "type": "stat",
   "description": "RDMA write throughput in bytes per second.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fcvi_rdma_write_throughput{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "FCVI Write IOPs",
   "type": "stat",
   "description": "Number of RDMA write I/Os issued per second.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(fcvi_rdma_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "gauge",
   "description": "Average processor utilization across all processors in the system.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_avg_processor_busy{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "Max Disk Utilization Per Aggregate",
   "type": "gauge",
   "description": "The utilization percent of the disk. aggr_disk_max_busy is the maximum of [disk_busy](#disk_busy) for label `aggr`.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(aggr_disk_max_busy{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "MetroCluster FCVI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Latency",
     "type": "timeseries",
     "description": "Average RDMA write I/O latency per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (node) (\n  fcvi_rdma_write_avg_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "timeseries",
     "description": "Average RDMA write throughput in bytes per second per node.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by (node) (\n  fcvi_rdma_write_throughput{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write IOPs",
     "type": "timeseries",
     "description": "Average Number of RDMA write I/Os issued per second per node.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (node) (fcvi_rdma_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Hard Reset Count",
     "type": "timeseries",
     "description": "Total Number of times hard reset of FCVI adapter got issued per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by (node) (fcvi_hard_reset_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Soft  Reset Count",
     "type": "timeseries",
     "description": "Total Number of times soft reset of FCVI adapter got issued per node.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (fcvi_soft_reset_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Link Failure Count",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported link failure count per node.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_link_failure_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Loss of Signal Count",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported loss of signal count per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_loss_of_signal_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Loss of Sync Count",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported loss of sync count per node.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_loss_of_sync_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "SyStatDiscardFrames Value",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported SyStatDiscardFrames value per node.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_systat_discard_frames{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Invalid CRC Count",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported invalid crc count per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_invalid_crc_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Invalid Transmit Word Count",
     "type": "timeseries",
     "description": "Total Number of times Firmware reported invalid transmit word count per node.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (node) (\n  fcvi_firmware_invalid_transmit_word_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\n)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster Iwarp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPs",
     "type": "timeseries",
     "description": "Average Number of RDMA I/Os issued per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (node) (iw_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read IOPs",
     "type": "timeseries",
     "description": "Average Number of RDMA read I/Os issued per node.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (node) (iw_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write IOPs",
     "type": "timeseries",
     "description": "Average Number of RDMA write I/Os issued per node.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg by (node) (iw_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Average Latency",
     "type": "timeseries",
     "description": "Average RDMA I/O latency per node.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (node) (iw_avg_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Plexes by Disk Utilization",
     "type": "timeseries",
     "description": "The utilization percent of the disk. plex_disk_busy is disk_busy aggregated by plex.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "plex_disk_busy{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      plex_disk_busy{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Plexes by Disk Utilization",
     "type": "table",
     "description": "The utilization percent of the disk. plex_disk_busy is disk_busy aggregated by plex.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_join(\n    plex_disk_busy{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"},\n    \"Field\",\n    \".\",\n    \"cluster\",\n    \"aggr\",\n    \"plex\"\n  )\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      label_join(\n        plex_disk_busy{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"},\n        \"Field\",\n        \".\",\n        \"cluster\",\n        \"aggr\",\n        \"plex\"\n      )[3h:] @ end()\n    )\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Plexes by User Reads",
     "type": "timeseries",
     "description": "Number of disk read operations initiated each second for retrieving data or metadata associated with user requests. plex_disk_user_reads is [disk_user_reads](#disk_user_reads) aggregated by `plex`.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "plex_disk_user_reads{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      plex_disk_user_reads{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Plexes by User Writes",
     "type": "timeseries",
     "description": "Number of disk write operations initiated each second for storing data or metadata associated with user requests. plex_disk_user_writes is [disk_user_writes](#disk_user_writes) aggregated by `plex`.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "plex_disk_user_writes{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      plex_disk_user_writes{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Plexes by User Read Latency per 4KB IO",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user read operations. plex_disk_user_read_latency is [disk_user_read_latency](#disk_user_read_latency) aggregated by `plex`.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "plex_disk_user_read_latency{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      plex_disk_user_read_latency{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Plexes by User Write Latency per 4KB IO",
     "type": "timeseries",
     "description": "Average latency per block in microseconds for user write operations. plex_disk_user_write_latency is [disk_user_write_latency](#disk_user_write_latency) aggregated by `plex`.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "plex_disk_user_write_latency{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      plex_disk_user_write_latency{aggr=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}}.{{aggr}}.{{plex}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Tape Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Adapters by Read Data",
     "type": "timeseries",
     "description": "Bytes read through a host adapter.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "hostadapter_bytes_read{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      hostadapter_bytes_read{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{hostadapter}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Adapters by Write Data",
     "type": "timeseries",
     "description": "Bytes written through a host adapter.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "hostadapter_bytes_written{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      hostadapter_bytes_written{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{node}} - {{hostadapter}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster FibreBridge/Array",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Latency from FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The average latency of I/O read operations sent from this controller to the indicated target port.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "path_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read Data from FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The average read throughput in kilobytes per second read from the indicated target port by the controller.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "path_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Read IOPs from FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The number of I/O read operations sent from the initiator port to the indicated target port.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "path_read_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Latency to FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The average latency of I/O write operations sent from this controller to the indicated target port.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "path_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write Data to FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The average write throughput in kilobytes per second written to the indicated target port by the controller.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "path_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Write IOPs to FibreBridge/Array WWPN",
     "type": "timeseries",
     "description": "The number of I/O write operations sent from the initiator port to the indicated target port.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "path_write_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MetroCluster Diagnostics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
     "options": {
      "content": "This panel requires ONTAP 9.12+. The APIs are only available via REST. You must enable the REST collector in your `harvest.yml` config.<br>\nSee https://github.com/NetApp/harvest/wiki/Troubleshooting-Harvest#why-do-i-have-metrocluster-diagnostics-panel-empty-in-metrocluster-dashboard for more details."
     }
    },
    {
     "title": "Metrocluster Cluster Diagnostics Check Details",
     "type": "table",
     "description": "This panel displays cluster level diagnostics status detail of Metrocluster.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "metrocluster_check_cluster_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\"}"
      }
     ]
    },
    {
     "title": "Metrocluster Node Diagnostics Check Details",
     "type": "table",
     "description": "This panel displays node level diagnostics status detail of Metrocluster.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "metrocluster_check_node_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Metrocluster Aggregate Diagnostics Check Details",
     "type": "table",
     "description": "This panel displays aggregate level diagnostics status detail of Metrocluster.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "metrocluster_check_aggr_status{aggregate=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Metrocluster Volume Diagnostics Check Details",
     "type": "table",
     "description": "This panel displays volume level diagnostics status detail of Metrocluster.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "metrocluster_check_volume_status{aggregate=~\"$Aggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\"}"
      }
     ]
    }
   ]
  }
 ]
}